### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by xiaozewa** [AtomCrafty/yukatool2#6]
hello~
When I load the project, I am prompted that some files are missing
they are:
Yuka.Patch/Yuka.Patch.csproj
Yuka.Core/app.config
Yuka.Cli/Commands/DisassembleCommand.cs

**Comment by AtomCrafty** [comment]
Thanks for bringing this to my attention. I must have accidentally committed changes to the project files that reference experimental features not included in the public release. It should be fixed now.
