### ISSUE TITLE
About word-wrap

### ISSUE THREAD

**Issue by mingyue2108** [AtomCrafty/yukatool2#7]
Hello AtomCrafty, thanks for this amazing work. But may I ask you a question? How do you wrap words?

**Comment by AtomCrafty** [comment]
Yukatool does not have any builtin support for word wrapping, because in the project I originally developed it for I ended up modifying the engine to wrap words at runtime. Feel free to contact me on Discord (@atomcrafty), I'll try to see how I can help.
